### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by greg-bioinfo** [ksugar/samapi#20]
Hi,
When i try to launch the samapi servor i have this error:
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Do you know why ?
thank you

**Comment by ksugar** [comment]
Hi @greg-bioinfo, thank you for trying samapi.

As far as I investigated, the error usually indicates a problem with reading the PyTorch model file, often due to corruption or incomplete downloads.

Did the error message have a specific name of the file that has a problem?

Perhaps, you can try removing the ~/.samapi/ directory located under your home directory, and restarting the samapi server.

Please let me know if you need further help.

**Comment by greg-bioinfo** [comment]
Thank you a lot,
I think the file was not downloaded correctly.
But i have a new error now:
![image](https://github.com/user-attachments/assets/b0fcb14d-5ee5-4dc3-84f3-9761d6d8a352)
![image](https://github.com/user-attachments/assets/35002fb7-6cb9-46f9-ba7b-7bcf83031ff0)

**Comment by ksugar** [comment]
Hi @greg-bioinfo, could you try adding the trailing slash to the server URL?
The error should be fixed with this change.

```
http://localhost:8000/sam/
```

**Comment by greg-bioinfo** [comment]
It works 
thank you very much for the quick replies !
